### ISSUE TITLE
Explain bootstrapping better

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#129]

**Comment by kirjs** [comment]
Just throwing feedback from the bootstap slide:

Maybe helpful to explain the idea of bootstrapping a root module, as module can hold other modules? I feel the bootstrapModule part is redundant if i have 1 module in the whole app and just put everything in the same module.

Bootstrap/16: Explanation on formats for Builtin module vs user defined module might be useful. @angular for builtin vs ./app.module (relative path) for use defined ones.

Is there a way to bootstrap multiple modules together?If yes, showing the syntax may be helpful here on Bootstrap/16

**Comment by tessaSAC** [comment]
Moving to #494
