### ISSUE TITLE
Display a diagram of what was learnt at the end of each lesson

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#147]
User comment: 
After every module or section - having a visual representation showing how everything works together to show how the App works. Maybe a step by step slide or single page view of everything.

Maybe show a diagram or something?

**Comment by tessaSAC** [comment]
Is this different from the overview/review slide?

**Comment by kirjs** [comment]
Kind of the same, or more structured, this is Zo's idea, this task is kinda very blurry. 

Basically the idea is to see the whole picture after each milestone.

**Comment by tessaSAC** [comment]
The whole picture as in website in its current state? So kind of related to #37 and #200?

**Comment by kirjs** [comment]
No, like a big diargam of what someone learned

**Comment by tessaSAC** [comment]
Ooo 🙀

**Comment by kirjs** [comment]
I'll explain in person, haha

**Comment by aorinevo** [comment]
Maybe Giffy?
