### ISSUE TITLE
Worthwhile to tell people that they can mouse over the red lines. That's the cool part of having TypeScript errors inside of your editing experience

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#237]
Worthwhile to tell people that they can mouse over the red lines. That's the cool part of having TypeScript errors inside of your editing experience 
Author: John Paul
[Slide](/typescript/types-primitives)

**Comment by tessaSAC** [comment]
Any suggestions on a good way to grab the code part?

**Comment by kirjs** [comment]
I'm afraid direct dom manipulation before showing intro.js is the fastest way as ugly as it sounds. 
This also should happen in the mini exercise, as it's the first instance of an error.

**Comment by tessaSAC** [comment]
😱😱😱

Yeah, I'd been looking at the mini exercise and realizing I couldn't put the attribute directly in there 😂😭

**Comment by tessaSAC** [comment]
Should we close this issue @kirjs?
