### ISSUE TITLE
Explain when to use public, private, this

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#253]
The slides had a private access modifier but the solution here was a public one, and there was no explanation of when to use either. Also, there is no explanation of when to use "this" inside the component. 
Author: Neill Perry
Slide: [Local](http://localhost:4200/dependency-injection/exercise),  [Public](https://angular-presentation.firebaseapp.com/dependency-injection/exercise)

**Comment by kirjs** [comment]
Can we explain this better (pun intended)?

**Comment by kirjs** [comment]
Another comment: Could use clarification that videoService needs to be invoked as this.videoService inside the class

**Comment by tessaSAC** [comment]
Moving to #494
