### ISSUE TITLE
and that you need to set its type as VideoItem

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#257]
and that you need to set its type as VideoItem 
Author: Sojung Park
Slide: [Local](http://localhost:4200/component-tree/exercise-1),  [Public](https://angular-presentation.firebaseapp.com/component-tree/exercise-1)

**Comment by kirjs** [comment]
Ideally add a test for the type of video
@RingoKam @sean-r-martin Let me know if you want to look into that :)

**Comment by tessaSAC** [comment]
Related to #415
