### ISSUE TITLE
Cannot choose tab in Safari

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#264]
Cannot choose tab in Safari
Author: Eric Tang
Slide: [Local](http://localhost:4200/templates/exercise-2),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-2)

**Comment by kirjs** [comment]
Progress bar goes above tabs in safari for some reason

**Comment by tessaSAC** [comment]
kind of reverse of #335
