### ISSUE TITLE
Elaborate on inferring types

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#288]
should we explain why (explicit) typing isn't necessary in this exercise?
Author: tessaSAC
Slide: [Local](http://localhost:4200/templates/exercise-2),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-2)

**Comment by kirjs** [comment]
@tessaSAC Can you elaborate?

**Comment by tessaSAC** [comment]
I think i was referring to whether we should empathize the implicit typing here`title = 'MewTube'`; this was one of the ones i considered deleting (when I didn't know how to use the feedback buttons)

**Comment by kirjs** [comment]
Would be nice to have, marking as low priority
