### ISSUE TITLE
Better explain template variables before this exercise.

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#292]
Better explain template variables before this exercise.
Author: Eric Tang
Slide: [Local](http://localhost:4200/templates/exercise-2),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-2)

**Comment by kirjs** [comment]
Would be nice to have an exercise for it (or maybe through away template vars at all?)

**Comment by tessaSAC** [comment]
Moving to #494
