### ISSUE TITLE
Clean up circle/Box slide

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#313]
the color of the circle is black instead of green.

it would also be nice to be able to edit the code on this slide
Author: Daniel Taveras
Slide: [Local](http://localhost:4200/component-tree/recap),[Public](https://angular-presentation.firebaseapp.com/component-tree/recap)

**Comment by kirjs** [comment]
make it green

**Comment by tessaSAC** [comment]
probably related to #312

**Comment by kirjs** [comment]
circleColor isn't used on <app-circle>, in the BoxComponent's template
Author: Daniel Taveras
Slide: [Local](http://localhost:4200/component-tree/parent-child-component),[Public](https://angular-presentation.firebaseapp.com/component-tree/parent-child-component)
