### ISSUE TITLE
also line breaks don't work in feedback, probably needs a "white-space: pre-line" in its stylesheet

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#317]
also line breaks don't work in feedback, probably needs a "white-space: pre-line" in its stylesheet
Author: Will
Slide: [Local](http://localhost:4200/typescript/classes),[Public](https://angular-presentation.firebaseapp.com/typescript/classes)

**Comment by kirjs** [comment]
Use CSS to get line breaks back in the comments.

**Comment by aziz512** [comment]
https://github.com/nycJSorg/angular-presentation/pull/592
