### ISSUE TITLE
Better explain decorator syntax (specifically: no semicolon)

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#320]
Since it seems that adding a semicolon after the Component decorator declaration breaks the Angular binding, it would be cool to point out in the slides that in this case, the absence of a semicolon is an important requirement and not just a syntax thing. 
Author: Christine
Slide: [Local](http://localhost:4200/create-first-app/exercise-component),[Public](https://angular-presentation.firebaseapp.com/create-first-app/exercise-component)

**Comment by kirjs** [comment]
NIce to have, but low priority

**Comment by tessaSAC** [comment]
Moved to #494
