### ISSUE TITLE
Set code editor overflow to always visible?

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#334]
Possible to affix the horizontal scrollbar to the bottom of the code window rather than needing to scroll to the bottom of the code to get to it (see main.ts)?
Author: Angelo
Slide: [Local](http://localhost:4200/templates/exercise),[Public](https://angular-presentation.firebaseapp.com/templates/exercise)

**Comment by kirjs** [comment]
Don't understand

**Comment by tessaSAC** [comment]
think he means something like `overflow-x: visible
<img width="587" alt="screen shot 2017-05-14 at 1 09 51 pm" src="https://cloud.githubusercontent.com/assets/20037396/26036156/a5dd96f0-38a6-11e7-92ef-2bf2c68ac5ed.png">
<img width="594" alt="screen shot 2017-05-14 at 1 09 55 pm" src="https://cloud.githubusercontent.com/assets/20037396/26036155/a5db73ac-38a6-11e7-9adf-390b479e85e5.png">


`

**Comment by kirjs** [comment]
Ah, I see, isn't it possible to actually scroll with the touchpad / arrow keys ?

**Comment by kirjs** [comment]
ah, ok I see now

**Comment by kirjs** [comment]
My understanding is that this has been fixed?

**Comment by tessaSAC** [comment]
afaik we gave up on it is that the same thing lol
