### ISSUE TITLE
when you click on main.ts on this slide, the code snippet cuts off the top row of file tabs.

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#335]
when you click on main.ts on this slide, the code snippet cuts off the top row of file tabs.
Author: Christine
Slide: [Local](http://localhost:4200/templates/exercise),[Public](https://angular-presentation.firebaseapp.com/templates/exercise)

**Comment by kirjs** [comment]
I think tabs should not be scrolled with the content

**Comment by kirjs** [comment]
cc @UmaMoiseenko

**Comment by tessaSAC** [comment]
Related to #299
