### ISSUE TITLE
Also, this particular detail is surprisingly easy to miss right now. Maybe add another slide before showing the wrong/long way to do this, and then th

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#341]
Also, this particular detail is surprisingly easy to miss right now. Maybe add another slide before showing the wrong/long way to do this, and then this?
Author: Will
Slide: [Local](http://localhost:4200/typescript/classes-access-modifier),[Public](https://angular-presentation.firebaseapp.com/typescript/classes-access-modifier)

**Comment by kirjs** [comment]
Why not, low priority

**Comment by tessaSAC** [comment]
meaning the export part?

**Comment by kirjs** [comment]
Show that
```TypeScript
constructor(public name: string){
    // Later we'll have code here
  }`
is just a shortcut for: 
```TypeScript
name: string;
constructor(name: string){
  this.name = name;
  }`

That's very low priority though.
