### ISSUE TITLE
Better explain typing arrays and change example

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#359]
Might be helpful to have a comment explaining this. I had to stare at it for a while before figuring out that betterFruit is an instance of type Array<Fruit> / an array containing one Fruit object.
Author: Saif Tase
Slide: [Local](http://localhost:4200/typescript/types-arrays),[Public](https://angular-presentation.firebaseapp.com/typescript/types-arrays)

**Comment by kirjs** [comment]
@sean-r-martin Argee, this is inconsistent,
also fruit are confusing as example, because it's hard to say if they are plural.

**Comment by tessaSAC** [comment]
Seems like this was addressed by both overlapping issues and merged changes
