### ISSUE TITLE
Add in-depth explanation of interfaces

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#374]
What is an interface? Maybe a link should be added here or an extra slide describing interfaces
Author: Marc Aupont
Slide: [Local](http://localhost:4200/typescript/types-more),[Public](https://angular-presentation.firebaseapp.com/typescript/types-more)

**Comment by kirjs** [comment]
Actually there can be people not familiar with interfaces, need to clarify that somehow.

**Comment by tessaSAC** [comment]
Moving to #494
