### ISSUE TITLE
[Done] Don't we have to say
this.guests = guests
inside of the constructor???

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#379]
Don't we have to say
this.guests = guests
inside of the constructor???
Author: Marianna
Slide: [Local](http://localhost:4200/typescript/end),[Public](https://angular-presentation.firebaseapp.com/typescript/end)

**Comment by kirjs** [comment]
I think this might be a duplicate, but can't find the other bug

**Comment by kirjs** [comment]
another one on context: 
Someone may not figure out that to call the `search` function in the constructor they need to call it using `this`(this.search("") instead of just search(""))
Author: Emmanuel Geanrd
Slide: [Local](http://localhost:4200/templates/exercise-3),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-3)

**Comment by tessaSAC** [comment]
Maybe related to #270 and #434 (same as last comment)?

**Comment by kirjs** [comment]
It would be nice to have a deeper explanation about constructor and what purpose it serves.
Author: Marianna
Slide: [Local](http://localhost:4200/typescript/exercise),[Public](https://angular-presentation.firebaseapp.com/typescript/exercise)
