### ISSUE TITLE
Succinctly explain Dependency Injection

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#384]
This example does not really make a lot of sense to me. As a TypeScript newbie, I'm not exactly sure what's going on in the left pane that Angular simplifies.
Author: Saif Tase
Slide: [Local](http://localhost:4200/dependency-injection/comparison),[Public](https://angular-presentation.firebaseapp.com/dependency-injection/comparison)

**Comment by kirjs** [comment]
Need better explanation for the benefits of dependency injection

**Comment by tessaSAC** [comment]
related to #148?

**Comment by kirjs** [comment]
So far this whole section is making no sense to me because it is only grazed over. There is a lot of information here but it is not delved into deeply enough.
Author: Maria Campbell
Slide: Local,Public

**Comment by tessaSAC** [comment]
Moving to #494
