### ISSUE TITLE
Spent nearly 15 minutes trying to figure out why i was receiving an error on line 8. Turns out i spelled bootstrap with a capital "B" instead of a low

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#387]
Spent nearly 15 minutes trying to figure out why i was receiving an error on line 8. Turns out i spelled bootstrap with a capital "B" instead of a lower case b.
Author: Angel A Cruz
Slide: [Local](http://localhost:4200/create-first-app/exercise-module),[Public](https://angular-presentation.firebaseapp.com/create-first-app/exercise-module)

**Comment by kirjs** [comment]
low priority

**Comment by tessaSAC** [comment]
related to #129?
