### ISSUE TITLE
Better explain const and let

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#405]
const: Might also be worthwhile to clarify that it doesn't mean that the values of objects assigned to const can't change. For ex: const a = []; a.push(1) is allowed. 
Author: Joseph Barlan
Slide: [Local](http://localhost:4200/typescript/types-primitives),[Public](https://angular-presentation.firebaseapp.com/typescript/types-primitives)

**Comment by kirjs** [comment]
I don't understand the relevance of it as I think it's out of the scope and is too hard to explain in simple words, but I've been getting a lot of feedback about it. 
Any takers?

**Comment by tessaSAC** [comment]
Seems like more of a vanillaJS thing than a TS or Angular thing to me; was confused that `let`/`const` was in there at all personally 😬

**Comment by kirjs** [comment]
It seems weird to use vars in examples, and when using let/const a lot of people ask about what they are for.

Marking as low priority for now

**Comment by tessaSAC** [comment]
meant explanation of `let`/`const` 😬😬😬

**Comment by tessaSAC** [comment]
related to #311

**Comment by kirjs** [comment]
Does the let here describe es6 let or its just string "let"
Author: Mohammad Khan
Slide: [Local](http://localhost:4200/templates/conditional-display-ngfor),[Public](https://angular-presentation.firebaseapp.com/templates/conditional-display-ngfor)

**Comment by tessaSAC** [comment]
Moving to #494
