### ISSUE TITLE
Further explain setting Array types

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#415]
Is specifying VideoItem[] type necessary here:
videos: VideoItem[] = []; ?
can it be 
videos = [] ?
Author: Marianna
Slide: [Local](http://localhost:4200/templates/exercise-2),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-2)

**Comment by kirjs** [comment]
Low priority, but would be nice to elaborate somewhere

**Comment by tessaSAC** [comment]
related to #359?

**Comment by tessaSAC** [comment]
Moving to #494
