### ISSUE TITLE
Improve code editor UI for multiple tabs

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#435]
When the number files gets to be more than 4 or 5 it might better to just show the ones that need to be worked on to pass the exercise.
Author: Emmanuel Geanrd
Slide: [Local](http://localhost:4200/dependency-injection/exercise),[Public](https://angular-presentation.firebaseapp.com/dependency-injection/exercise)

**Comment by tessaSAC** [comment]
Maybe just keep them in file tree? Or related to/could be addressed by #299?

**Comment by kirjs** [comment]
Looks like we're ending up reimplementing whatever every other IDE Is doing :)

**Comment by kirjs** [comment]
This is in
