### ISSUE TITLE
Mentioning that import is not just for files is great tip!

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#441]
Mentioning that import is not just for files is great tip!
Author: Emmanuel Geanrd
Slide: [Local](http://localhost:4200/typescript/import),[Public](https://angular-presentation.firebaseapp.com/typescript/import)

**Comment by kirjs** [comment]
don't understand

**Comment by kirjs** [comment]
Followed up with Emmanuel

**Comment by edgenard** [comment]
I just wanted to highlight that importing is not just for classes or functions, but you can import variables and interfaces defined in another file.
