### ISSUE TITLE
Request to add in-depth explanation of browser events

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#446]
I think someone doing this will have to be familiar with the concepts of browser events already. So it will probably more difficult for someone completely new to web development or even front-end frameworks.
Author: Emmanuel Geanrd
Slide: [Local](http://localhost:4200/templates/exercise-2),[Public](https://angular-presentation.firebaseapp.com/templates/exercise-2)

**Comment by tessaSAC** [comment]
Related to #75?

**Comment by tessaSAC** [comment]
Moving to #494. Hey, this is the guy who taught me at RailsBridge! 😄
