### ISSUE TITLE
Use template, or something else to make sure that slides are not rendered until needed.

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#456]

**Comment by MichaelSolati** [comment]
Could load templates programmatically. Only keep 3 in dom at a time (current, previous, and next)

**Comment by MichaelSolati** [comment]
So I have something working here, but this will actually be a more complicated issue than not. Essentially the big issue is that if the structural directive prevents the slide from being created then the slide will not get registered in the `PresentationComponent`. So I'm having the directive register the slide (and watch the index) of the `PresentationComponent` but so far I have a few small issues I need to figure out... (like the progress bar is kind of broken). 

So yes it can work, it also requires a lot of work to get it to work.

**Comment by kirjs** [comment]
This has been merged
