### ISSUE TITLE
Enforce "Import Destructuring Spacing" in tslint

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#471]
# Motivation
Right now there is no consistent way to handle spaces in destructured imports, this introduces some noise in commits as right now we have no spaces, but angular CLI as well as some formatters actually add spaces. 

Also ts-lint only validates the case with spaces

# Solution
- [x] Add spaces across the codebase
- [x] Add TS-lint rule
- [x] Document the configuration for the websorm and VSCode

# Editor configuration
Intellij/Webstorm
`Settings -> Code Style -> TypeScript -> Spaces Tab -> Check “ES6 import/export braces”`

see also
https://github.com/mgechev/codelyzer/issues/40
https://stackoverflow.com/questions/41447602/tslint-remove-missing-whitespace-rule-on-import

**Comment by tessaSAC** [comment]
@RingoKam you can do third checkbox VSC part lol 😬

**Comment by tessaSAC** [comment]
@kirjs You did the first task right?

**Comment by kirjs** [comment]
I did

**Comment by kirjs** [comment]
Assigning to ringo kam for an advice on how this could be done with VS Code

**Comment by kirjs** [comment]
Added to contributing md, assume vs code does that

**Comment by RingoKam** [comment]
Oh didn't see this until now lol
