### ISSUE TITLE
Add popups with explanation for more complex terms 

### ISSUE THREAD

**Issue by bruno78** [nycJSorg/angular-presentation#487]
- [ ] Find a beginner and ask them to point out all the complex words
- [ ] Write explanations for all the complex words
- [ ] Add popups for the explanations

**Comment by tessaSAC** [comment]
At first I thought we could/would need to make a directive for the popups, but it seems like we could just use introjs hints for this, especially since we now have the CSS file globally... what do you think @kirjs @bruno78?

**Comment by kirjs** [comment]
Can you do intro.js on hover?

**Comment by bruno78** [comment]
It seems a good idea. Do you know if we can use highlighting (on words) instead of dots?

**Comment by tessaSAC** [comment]
Hints is on hover @kirjs 

@bruno78 You can probably edit the css but I don't know enough about highlighting to say; if having grabbed a word you can say that word should be highlighted then probably. If you have to draw the box yourself it's probably more trouble than it's worth. And that's assuming you can grab the word 😂😂😖

**Comment by kirjs** [comment]
bag bankruptcy
