### ISSUE TITLE
back button is broken

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#493]

**Comment by MichaelSolati** [comment]
A little more details please? The only place where I've seen the back button being an issue or an annoyance is when your go to a new section and you are routed to the path 0 then it immediately changes to the slide id. I'm assuming we're complaining about the second location state that requires you to press the back button twice to actually go back?

**Comment by tessaSAC** [comment]
Is this about the swiping function? When I try to select text in the code editor it changes the slide 😂

**Comment by kirjs** [comment]
cc @barlanj
