### ISSUE TITLE
Find the way to publish this as a library

### ISSUE THREAD

**Issue by kirjs** [nycJSorg/angular-presentation#5]
May require some tinkering. 

Here's a sample library from an ng-conf talk: 
https://github.com/jasonaden/simple-ui-lib
here's semi-related angular-cli issue: 
https://github.com/angular/angular-cli/issues/1692

**Comment by matheo** [comment]
Interesting too:
https://github.com/angular/angular.io/pull/2758
I will review that, and publish a basic library too
so we could share findings ;)
