### ISSUE TITLE
VUE: discuss course structure

### ISSUE THREAD

**Issue by tessaSAC** [nycJSorg/angular-presentation#509]
(see [google doc](https://docs.google.com/document/d/1Vvz-ywHbQIrLLpbLZvPeXG-MYyJhItORBfzmjZPqNUk/edit) for more details/what we have so far)

**Comment by prestonvanloon** [comment]
Link to doc?

**Comment by RingoKam** [comment]
@prestonvanloon 
https://docs.google.com/document/d/1Vvz-ywHbQIrLLpbLZvPeXG-MYyJhItORBfzmjZPqNUk/edit

**Comment by tessaSAC** [comment]
Updated the google doc with an outline of the Vue doc's guide. Can revisit with the advanced section if/when necessary.

It goes without saying that some parts within the guide alone can be refactored (e.g. explaining what `v-model` is syntactic sugar for when explaining `v-model`, but outside of that this can also serve as a reference to consider during discussion of the Vue codelab's (potential) restructuring.

**Comment by tessaSAC** [comment]
This week's updates: [VueTube](https://jsfiddle.net/tessap/jn986wqs/15/) and [Vue Pokémon](https://vue-pokemon.herokuapp.com/#/) ([source code](https://github.com/matt-oconnell/vue-pokemon/tree/master/src)) exercise examples

**Comment by kirjs** [comment]
bug bankruptcy
