### ISSUE TITLE
Modularize Presentations

### ISSUE THREAD

**Issue by MichaelSolati** [nycJSorg/angular-presentation#530]
So moving forward it may be appropriate to break apart this application into a few different applications. Things like the Typescript or Angular (and upcoming React and Vue) could/should be separate codelabs all together.

Things like the slides and some of the directives used can be made into their own Angular module/package (installable on NPM and stuff) and we can keep that separate of the code labs themselves as a common resource.

Before this happens I would love to get thoughts from you guys as I will be starting to break apart the code next week and try to modularize it the best that I can.

**Comment by kirjs** [comment]
Start with moving out angular-presentation maybe? And then it'll be kind more clear
